### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by niels-vormenvorm** [jmcgaha/craft-boilerplate#1]
Hi,

Thank you for the great boilerplate, it really helps me to start practicing with Tailwind + craft CMS. i can't seem to create a custom css. I've added a custom css but my custom css (.btn) doesn't get added to the used css. I've created this build script, but also that didn't work:
"build": "tailwind build src/custom.css -o public/lib/css/custom.css"

Thank you for the help.

**Comment by niels-vormenvorm** [comment]
Found it..

**Comment by cmartinespinosa** [comment]
@niels-vormenvorm
I have the same proble...how did you solve it?. Thxs

**Comment by niels-vormenvorm** [comment]
@cmartinespinosa 
You can put an import in 'assets' -> 'sass' -> 'app.scss'

`@import 'main';`

And then add a main.scss in the same folder
